### ISSUE TITLE
OOTB cssmin support will clobber precompiler//Sass (SCSS) output

### ISSUE THREAD

**Issue by myabc** [stefanpenner/ember-app-kit#153]
### reproduction

Add Sass (SCSS) support to the project, with the workaround detailed in #152.

Add both precompiled (SCSS) and regular .css stylesheets.

`app/styles/application.scss`:

``` scss

body {
  background-color: red;
}

h1 {
  color: white;
}
```

`app/styles/test.css`:

``` css
body {
  background-color: blue;
}
```

The generated `public/assets/app.css` will only contain the contents of `app/styles/test.css`. Removing the regular .css file will cause the cssmin task to be skipped.
